default_model_config:
  patch_size: 1000
  layer_count: 3
  attn_head_count: 12
  embedding_dim: 768
  dropout: 0.1
  bias: false
  norm_eps: 1.e-5
  rescale_norm_outputs: false
  output_head_count: 16
  output_head_classes: 256
  shared_head: true
default_training_config:
  training_steps: 5000
  base_lr: 5.e-4
  lr_scheduler_name: cosine_decay
  lr_scheduler_kwargs:
    warmup_steps: 500
    const_steps: 0
  beta_1: 0.9
  beta_2: 0.99
  eps: 1.e-8
  weight_decay: 1.e-4
  grad_clip: 1.0
  dtype: bf16-mixed
  compile: true
datamodule_config:
  val_prop: 0.1
  train_batch_size: 512
  eval_batch_size: 512
  num_workers: 8
  pin_memory: false
  persistent_workers: false
  prefetch_factor: 1
dataset_config:
  target: subbytes
  store_in_ram: true