gautschi:
  openwebtext: /scratch/gautschi/jgammell/openwebtext
  imagenet: null
  ascadv1: /scratch/gautschi/jgammell/ascadv1
  ascadv2: /scratch/gautschi/jgammell/ascadv2
  jester: /scratch/gautschi/jgammell/pytorch_boilerplate/resources/jester
ee350-csme-precision:
  openwebtext: /mnt/hdd/datasets/openwebtext
  imagenet: /mnt/hdd/datasets/imagenet
  imagenette: /mnt/hdd/datasets/imagenette
  ascadv1: /mnt/hdd/jgammell/leakage_localization/downloads/ascadv1
  ascadv2: /mnt/hdd/jgammell/leakage_localization/downloads/ascadv2
  jester: /home/jgammell/Desktop/pytorch_boilerplate/resources/jester