default_model_config:
  input_channels: 3
  input_spatial_dim: 128
  out_dim: 27
  patch_dim: 16
  max_input_temporal_dim: 32
  transformer_head_count: 3
  transformer_layer_count: 12
  transformer_hidden_dim: 192
  transformer_mlp_expansion_ratio: 4
  dropout: 0.0
  init_from_deit: tiny-distilled
  include_downsampled_patches: true
  sparse_inputs: true
  per_frame_patch_count: 1
  gumbel_estimator: hard
  gumbel_temp: 1.0
default_training_config:
  training_steps: 92700
  base_lr: 1.e-5
  lr_scheduler_name: cosine_decay
  lr_scheduler_kwargs:
    warmup_steps: 4635
    const_steps: 0
    warmup_lr_prop: 0.002
    final_lr_prop: 0.02
  beta_1: 0.9
  beta_2: 0.999
  eps: 1.e-8
  weight_decay: 1.e-2
  grad_clip: null
  compile: false
datamodule_config:
  train_batch_size: 128
  eval_batch_size: 256
  num_workers: 8
  pin_memory: true
  persistent_workers: false
  prefetch_factor: 2
  timestep_count: 32
dataset_config:
  dim: 128
  timesteps: 32