nn_arch: causal-vivit
dataset: jester
default_model_config:
  input_channels: 3
  input_spatial_dim: 128
  out_dim: 27
  max_input_temporal_dim: 8
  dropout: 0.0
  vit_conf: TINY
  pretrained_model: DEIT_T
  include_downsampled_patches: true
  sparse_inputs: true
  per_frame_patch_count: 8
  gumbel_temp: 1.0
default_training_config:
  training_steps: 20000
  base_lr: 1.e-5
  lr_scheduler_name: cosine_decay
  lr_scheduler_kwargs:
    warmup_steps: 1000
    const_steps: 10000
    warmup_lr_prop: 0.0
    final_lr_prop: 0.0
  beta_1: 0.9
  beta_2: 0.999
  eps: 1.e-8
  weight_decay: 0.0
  grad_clip: 1.0
  compile: true
datamodule_config:
  train_batch_size: 512
  eval_batch_size: 1024
  num_workers: 8
  pin_memory: true
  persistent_workers: false
  prefetch_factor: 1
dataset_config:
  dim: 128
  prepare: false